project_id = "puikkcvxnrjvgsbgldhx"

[functions.create-staff-user]
verify_jwt = false

[functions.sync-shows]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.ai-upsell]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.check-fraud]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false
